[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | amber.*
)/
'''

[tool.poetry]
name = "acpype"
version = "2021.12.21"
description = "ACPYPE - AnteChamber PYthon Parser interfacE"
authors = ["Alan Silva <alanwilter@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = { extras = ["jupyter"], version = "^21.12b0" }
pytest-cov = "^3.0.0"
mypy = "^0.920"
pdbpp = "^0.10.3"
ipdb = "^0.13.9"

[build-system]
requires = ["setuptools>=58", "wheel", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
